### ISSUE TITLE
How to prevent adding <script> with bootstrap?

### ISSUE THREAD

**Issue by adam-boduch** [view-components/grids#10]
I've started to use grids but I realized that it includes `<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" type="text/javascript"></script>` which is fine but I already added `<script>` with bootstrap and jQuery so I don't need to do it again. 

Is there any way to disable it and still use bootstrap styling?

P.S. Where can I find documentation? It's hard to use this package without docs...

**Comment by jazlopez** [comment]
I have noticed the js injected as well. Have you figured out how to stop adding bootstrap twice?

Prob. will have a look  to see the base code and see if can be just easily bypassed.

**Comment by adam-boduch** [comment]
No, I haven't. I got rid of grids.

**Comment by jazlopez** [comment]
Just stepped aside as well - went over the code and found it tightly coupled for what I need. 
For what it is worth, I've found this one easier to customize and break it apart - just started a project on top of it https://github.com/gbrock/laravel-table

**Comment by Nayjest** [comment]
Hi!
See https://github.com/view-components/view-components/blob/master/doc/cookbook.md

**Comment by jazlopez** [comment]
Thanks, this helps. wondering if you have consider it offer support for MDL specific classes anytime soon?

**Comment by Nayjest** [comment]
@jazlopez 
See https://github.com/view-components/grids#integrations

Actually I started from Google MDL when worked on customizations, but I removed it even from plans becouse:
1. Grids looked ugly with MDL (IMHO)
2. MDL has very specific markup in contrast with Foundation / Bootstrap / Semantic UI that usually requires just adding few classes.

Probably I just can't cook MDL right way.

If you have experience with MDL, you can contribute to view-components.
I and community would appreciate it.
If you can even share good grid markup example (with buttons, select & text inputs, pagination), it would be very helpful.

Some info about customizations:
Example of customization config: https://github.com/view-components/view-components/blob/master/resources/config/styling/semantic-ui.php
In this config keys are mapped to selectors, see https://github.com/view-components/view-components/blob/master/src/Customization/Configurable/TargetSelector.php, methods named as camelCased selectors prefixed by 'check'.
And values are operations, see https://github.com/view-components/view-components/blob/master/src/Customization/Configurable/Helper.php

**Comment by jazlopez** [comment]
@Nayjest i've forked components repo , will look forward to have something to contrib. regarding mdl on my spare time.
I'll keep in contact.

**Comment by Nayjest** [comment]
Ok, thanks =)
I'm closing this issue, if you will have a questions / proposals regarding MDL, submit new one please.
