### ISSUE TITLE
Example Routes for Demo 11_1

### ISSUE THREAD

**Issue by moebaca** [view-components/grids#13]
Hi,

I'm new to Laravel and think these components look great!

I was hoping alongside the demo code (specifically demo 11_1) you could provide me an example set of routes as well? Currently my knowledge on routing is basic at best and if I could see how you handle routing to do things like sorting and searching keywords on filtering that would help out very much.

Thanks!

**Comment by Nayjest** [comment]
Hi,

Route::get('my-grid', 'MyController@showGrid');

That's all, 
everything related to filtering / sorting are handled by Grids automatically

**Comment by Nayjest** [comment]
Did I answered your question?

**Comment by moebaca** [comment]
Good morning, 

I just got in for work. I am going to try this out again today. From what I remember I basically had my route setup so that the View was rendered with the grid when you hit the "'MyController@showGrid'" function in the routes. 

After I would click sort, filter, etc. the page would blow up with a stack trace. 

I will try and get it back to that state and post it for you to examine.

Thanks for your reply by the way! Great job on this.

**Comment by Nayjest** [comment]
Hi!
I'm closing this issue. If you still have a questions, submit new issues please.
