### ISSUE TITLE
Rows as clickable links.

### ISSUE THREAD

**Issue by dtyson** [view-components/grids#15]
Having trouble displaying url column rows as clickable links.
For example: new Column('link', $label = 'Asset Link'),

**Comment by Nayjest** [comment]
Hi!
Can you share more details / clarify your question? What is problem with displaying url column rows as clickable links?

**Comment by Nayjest** [comment]
See https://github.com/view-components/grids/blob/master/doc/cookbook.md

**Comment by dtyson** [comment]
Thanks the cookbook example helped a lot.  The value in the 'link' table was already a url.  We just needed to make it clickable.  The code below worked.

(new Column('link', $label = 'Asset Link'))->setValueFormatter(function($value) {
        return "<a href='{$value}' target=_blank>{$value}</a>";
    }),
