### ISSUE TITLE
PageTotalsRow() not displaying total COUNT

### ISSUE THREAD

**Issue by purnimap18** [view-components/grids#16]
In our GRID we are displaying table data from SQL database. Couple of the columns are email & name.
We are using the following code with PageTotalsRow but it just adds a blank row without displaying any COUNT.

new PageTotalsRow([
	'email' => function () {
		return 'Total Records';
	},
	'name' => PageTotalsRow::OPERATION_COUNT,
]),

Any help / pointers are greatly appreciated.

**Comment by Nayjest** [comment]
Hi!
Give me few minutes, I will test PageTotalsRow::OPERATION_COUNT on my grid

**Comment by Nayjest** [comment]
I reproduced bug. For some $operations it really just adds blank row.
I have meeting now and then during ~3 hours I will fix that.

**Comment by purnimap18** [comment]
Alright. Thank you very much for looking into this.

**Comment by Nayjest** [comment]
@purnimap18  update Grids to v0.5.2 and view-components to 0.25 to receive bugfix.

And thank you for reporting issue.

**Comment by purnimap18** [comment]
**@Nayjest**  Thank you so very much. That worked!
