### ISSUE TITLE
Problem with the OPERATOR_LIKE

### ISSUE THREAD

**Issue by pascualm4** [view-components/grids#19]
I have a basic grid with an only one FilterControl using the operator like. An give back the following error:
"Unsupported operator like"

This is my code
``$provider = new ArrayDataProvider($divisions->toArray());

            $input = new InputSource($_GET);
            $sortingInput = new InputOption('sort', $_GET);

            $grid = new Grid($provider, [
                new Column('id'),
                (new Column('name'))
                    ->setLabel(ucfirst(trans('messages.name')))
                ,
                (new Column('actions'))
                    ->setLabel(ucfirst(trans('messages.actions')))
                    ->setValueCalculator(function($row){
                        return "<a href='".route('divisions.show', [$row->id])."'><img src='/images/icon_ver_off.png' width='26'></a>
                            | <a href='".route('divisions.edit', [$row->id])."'><img src='/images/icon_edit_off.png' width='26'></a>
                            | <a href='".route('divisions.delete', [$row->id])."' onclick='return confirm('".trans('messages.delete')."')'><img src='/images/icon_eliminar_off.png' width='26'></a>
                            ";
                    })
                ,
                new FilterControl('name', FilterOperation::OPERATOR_LIKE, $input->option('name')),
                new PaginationControl($input->option('page', 1), 5),
                new ColumnSortingControl('id', $sortingInput),
                new ColumnSortingControl('name', $sortingInput),
            ]);``

I don't know what I'm doing wrong. Also always the grid print the following character by the end of the grid "}".

Thanks in advance.

**Comment by Nayjest** [comment]
ArrayDataProvider does not supports LIKE (it's hard to implement), use FilterOperation::OPERATOR_STR_CONTAINS

Please give me know if problem with  "}" remains after replacing FilterOperation::OPERATOR_LIKE  to FilterOperation::OPERATOR_STR_CONTAINS

**Comment by Nayjest** [comment]
Another note: unlike it's done in nayjest/grids, here FilterOperation::OPERATOR_LIKE don't wraps input with % charecters, it's designed to allow usage of placeholders that works with SQL like (%, ?) inside input.

So, FilterOperation::OPERATOR_STR_CONTAINS is equivalent to FilterOperation::OPERATOR_LIKE  from natyjest/grids (for data-providers that reads from DB it  adds LIKE "%{$value}%" to SQL )

**Comment by pascualm4** [comment]
The operator: OPERATOR_STR_CONTAINS works well. Thanks!

**Comment by Nayjest** [comment]
What about problem with  "}" . Does It disappeared when you fixed errors?
