### ISSUE TITLE
Не работает CSV Export

### ISSUE THREAD

**Issue by borelias** [view-components/grids#26]
Приветствую.
Добавил кнопку CSV-экспорта, однако при ее нажатии (в url добавляеться GET-переменная "csv" со значением "1") но далее ничего не происходит:
```
            new Part(
                new Tag('tr',[], [
                    (new Tag('td'))
						->addChild( new CsvExport($input('csv', $_GET)))
						->addChild(new ResetButton('Сбросить'))
						->addChild(new TagWithText('buttom', 'Фильтровать', ['type' => 'submit', 'onclick'=> 'var form = jQuery(this).parents().filter("form");form.submit(); return false;'])),
```

В качестве DataProvider используется массив:
```
        $provider= new ArrayDataProvider($clientsArr);
        $input = new InputSource($_GET);
		
		//echo '<pre>'.var_export($input('client_name'), 1).'</pre>';
		
		$grid = new Grid($provider, [
```

Все необходимые библиотеки подключены, ошибок нет.
http://prntscr.com/dhof3i

С уважением.

**Comment by Nayjest** [comment]
Привет. 
CSV Export нужно аттачить к гриду напрямую, чтобы вызвался метод attachToCompound, который уже добавляет в тот же грид другой компонент, который прерывает рендеринг грида и отдает вместо стандартного вывода CSV.

Чтобы запихнуть саму кнопку в другое место в верстке, можно воспользоваться методом 

$csvExport->setDestinationParentId($destinationParentId)

Ну или можно попробовать оставить как есть и вручную дергнуть $csvExport->attachToCompound где-нибуть до рендеринга грида, но я не уверен, что это не переместит саму кнопку.

**Comment by borelias** [comment]
Можете более подробно описать этот момент: 

> CSV Export нужно аттачить к гриду напрямую, чтобы вызвался метод attachToCompound, который уже добавляет в тот же грид другой компонент, который прерывает рендеринг грида и отдает вместо стандартного вывода CSV.

С ув.

**Comment by Nayjest** [comment]
```php
$grid->addChild($csv = new CsvExport($input('csv', $_GET)))
```
Если нужно поместить не в control_container, а в другой контейнер, то:
```php
$csv->setDestinationParentId($newParentId)
```
Если этот другой контейнер не реализует интерфейс PartInterface (часть составного объекта), то чтобы у него был ID, который использован выше, его можно завернуть в класс Part.
PartInterface  -- это интерфейс для компонентов, являющихся составными частями других компонентов, Part -- простая обертка над любым компонентом, реализующая этот интерфейс, собственно, позволяет хранить идентификатор компонента и идентификатор родительского компонента, чтобы при добавлении в составной объект (Compound), этот compound сам его поместил в дерево своих дочерних компонентов куда нужно.

**Comment by borelias** [comment]
Thanks)
