### ISSUE TITLE
Css class in PaginationControl, Ajax requests on filter form and Custom templates for TemplateFinder

### ISSUE THREAD

**Issue by developeruz** [view-components/grids#30]
- Добрый день, подскажите пожалуйста как добавить стили в PaginationControl
```php
$columns[] =  (new PaginationControl($input->option('page', 1), 5))
      ->setDestinationParentId('table_footer');

$grid = new Grid(
      $provider,
      $columns
  );
```
генерирует ul без класса `pagination` как в вашем примере [тут](http://view-components.herokuapp.com/index.php/demo9_0). Как добавить класс или сделать пейджинацию как [тут](http://view-components.herokuapp.com/index.php/demo4_4)?

- Так же, не смотря на `setDestinationParentId('table_footer')` пейджинация не перемещается в футер таблицы, а выводится до нее.
```html
<nav data-role="control-container" data-control="pagination">
    <ul>
...
</ul>
</nav>
<table><thead>...</thead>
<tbody>...</tbody>
<tfoot> тут пусто! </tfoot>
</table>
```
Подскажите пожалуйста что я делаю не так?

- И еще вопрос про ajax или pjax - есть ли готовая реализация для onchange элементов фильтра? 
- Я правильно понимаю, что фильтр на сегодняшний день может быть либо input либо select? Есть ли возможность заставить  `TemplateFinder` искать еще и в другой дирректории, т.к в вендор свой шаблон я добавить не могу (range к примеру для выбора диапазона значений)

**Comment by Nayjest** [comment]
Добрый день.
PaginationControl для рендеринга ссылок использует ViewComponents\ViewComponents\Component\Control\View\PaginationControlView 
Этот компонент рендрит шаблон 'controls/pagination' и внутри для каждой ссылки рендерит 'controls/pagination/link'.

Если вам нужно заменить эти шаблоны в PaginationControlView для конкретного грида, это можно сделать примерно так:
```php
$paginationControl->getView()
    ->setTemplateName('your_pagination_template')
    ->setTemplate('your_pagination_link_template');
```
Чтобы использовать php-шаблоны из какой-либо директории проекта, а не из vendors/view-components/resources/views, вам нужно ее зарегистрировать:

https://github.com/view-components/view-components/blob/master/doc/cookbook.md#3-using-custom-view-templates-and-overriding-core-templates

Это лучше сделать не в конкретном контроллере, а где-то в bootstrap / сервис-провайдере, так чтобы это работало для всего проекта.

Если вы хотите, чтобы ваши стили использовались для всего проекта в любой пейджинации,
не прописывайте конкретные шаблоны компоненту, а просто подмените шаблоны глобально своими кастомизированными.

* скопируйте в директорию с шаблонами, которую вы зарегистрировали resources/views/controls/pagination.php и resources/views/controls/pagination/link.php
так, чтобы они лежали в your_views_dir/controls/pagination.php и /controls/pagination/link.php соответственно

**Comment by Nayjest** [comment]
По поводу onchange элементов фильтра -- можно сделать так, чтобы при выборе значения из селекта, сразу сабмитилась форма, 
```php
$selectFilterControl->getView()->setDataItem('autoSubmit', true);
```
см. view-components\resources\views\select.php

в этом шаблоне есть след. логика:
```php
// support of auto-submitting form on value change
if (isset($autoSubmit) && $autoSubmit === true) {
    if (array_key_exists('onchange', $inputAttributes)) {
        $inputAttributes['onchange'] .= ';this.form.submit();';
    } else {
        $inputAttributes['onchange'] = 'this.form.submit()';
    }
}
```

**Comment by Nayjest** [comment]
```
Так же, не смотря на setDestinationParentId('table_footer') пейджинация не перемещается в футер таблицы, а выводится до нее.
```
Дело в верстке, в tfoot нужно сначала запихнуть 
```html
<tr>
    <td colspan="сколько там колонок">
       /// и только сюда пейджинатор
    </td>
</tr>
```

Для таких штук есть компонент SolidRow

Вот пример пейджинации перемещенной в футер:
https://github.com/view-components/grids/blob/master/tests/webapp/Controller.php#L190

**Comment by Nayjest** [comment]
А с каким фреймворком вы эти гриды используете?

**Comment by developeruz** [comment]
Спасибо, посмотрю. Использую для Laravel 5 и пока решила остановится на Nayjest/Grids. 
В целом вами проделана огромная работа! Лучшее из grid-ов под Laravel. Спасибо!

**Comment by Nayjest** [comment]
Спасибо за лестный отзыв =)
