### ISSUE TITLE
Layout y Page not found

### ISSUE THREAD

**Issue by h2jose** [view-components/grids#35]
I can't find how  this->layout and this->pages Class working.

**Comment by Nayjest** [comment]
If your question is about Demo Application -- see https://github.com/view-components/testing-helpers/blob/master/src/Application/Http/DefaultLayoutTrait.php

\ViewComponents\TestingHelpers\Application\Http\DefaultLayoutTrait designed only for internal testing. Don't use view-components/testing-helpers in production (it's dev-dependency, you should install your code to production without dev-dependencies).

If you are interested in Layout component, see https://github.com/view-components/view-components/blob/master/src/Component/Layout.php

But it's absolutely not neccessary for working with grids. Just render your grid using `render()` method of Grid instance.
