### ISSUE TITLE
Delete form

### ISSUE THREAD

**Issue by Gurzhii** [view-components/grids#8]
Got an issue here.

```
public function generate()
    {

        $provider = new EloquentDataProvider(PostEloquentModel::class);
        $input = $this->defaultInputSource();
        $grid = new Grid(
            $provider,
            [
                new TableCaption('Blog'),
                new Column('id'),
                new Column('title'),
                new Column('slug'),
                (new Column('edit'))
                    ->setValueCalculator(function ($row) {
                        return BaseGrid::generateEditFormButton($row->id, 'admin.blog.edit');
                    }),
                (new Column('delete'))
                    ->setValueCalculator(function ($row) {
                       return BaseGrid::generateDeleteFormButton($row->id, 'admin.blog.destroy');
                    }),
                new PaginationControl($input('page', 1), $this->page_size),
                new ColumnSortingControl('title', $input->option('sort')),
            ]
        );

        $customization = new BootstrapStyling();
        $customization->apply($grid);

        $this->setHtml($grid->render());

        return $this;
    }
```

Here is generateDeleteFormButton
```
 public static function generateDeleteFormButton($id = 0, $route = '')
    {
        return view('admin.partials.custom_grid_columns.delete_column', [
            'id' => $id,
            'route' => $route
        ]);
    }
```

and also delete_column view
```
{!! Form::open(['method' => 'DELETE', 'route' => [$route, $id]]) !!}
{!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
{!! Form::close() !!}
```

On first button i got no rendered form tag
https://monosnap.com/file/qTPHn3Z9JCnxo6JJogRLVuFqCBsL5A.png
and because of this flow my click expected as GET request https://monosnap.com/file/J5slnZgbyEIacj1mKnLvYIdUgfIL62.png
also nothing happed

**Comment by Gurzhii** [comment]
Also checked source, i got first form here
https://monosnap.com/file/IQkoFXqel9sSSlnugBay9VUCJvZEy4.png

**Comment by Gurzhii** [comment]
I think its because of im trying to render form in non-closed form https://monosnap.com/file/qMigzn5A9EkB2FfPWnCX5sh5NxIbtm.png

**Comment by Gurzhii** [comment]
I changed 
```
static::FORM_ID => new Part(
                new Tag('form', ['data-role' => 'managed_list_form']),
                static::FORM_ID,
                static::CONTAINER_ID
            ),
```
to
```
static::FORM_ID => new Part(
                new Tag('div', ['data-role' => 'managed_list_form']),
                static::FORM_ID,
                static::CONTAINER_ID
            ),
```

and all rendering like i'm expecting - https://monosnap.com/file/gsXmcNswCuPKhAh2zXP3ucOkQ5A8LL.png
for what are u using this form?

**Comment by Nayjest** [comment]
You create form inside another form (grids are placed into forms, but you can change that modifying components tree)

**Comment by Gurzhii** [comment]
What is your solution for delete button?

**Comment by Gurzhii** [comment]
Here is the answer:
if u need delete button works fine u need to include laravel.js(https://gist.github.com/soufianeEL/3f8483f0f3dc9e3ec5d9) and also did the trick with replacing your form by
```
<a href="{{ route($route, [$id])  }}" data-method="delete" data-token="{{csrf_token()}}" data-confirm="Are you sure?" class="btn btn-danger">Delete</a>
```

**Comment by Nayjest** [comment]
a) Place form for submitting "delete" request after (or before) grid and add onclick event for pushing deleted record ID into form & submitting it (looks like best way)

b) Detach "form" component from grid & attach to another place, for example inside "control_row" component (becouse there are all inputs that should be placed inside this form). (require no javascript, but you will have alot of sex with grids package)

c) Delete records by GET request, but you will need to make confirmation to avoid auto-visiting links  by some browser plugins & provide token for security reasons (looks overcomplicated, but all that security features can be optional depending on your business/quality requirements)

d) Send HTTP request for deleting record via ajax

**Comment by Nayjest** [comment]
Nice solution too, thanx for sharing

**Comment by Nayjest** [comment]
Also I started to work on documentation, that's drafts, so you will not find links ot it inside readme, but may be useful:

https://github.com/view-components/view-components/blob/master/doc/cookbook.md

https://github.com/view-components/view-components/blob/master/doc/components.md

**Comment by Nayjest** [comment]
Some advices:
* Don't modify core classes (anything inside vendors folder), you can extend it to create your own components
* Move logic to separate components. For example, instead of configuring actions column inside controller, you can create class extended from Column with all required options & use in grid.
* If you need to customize core services, there is dependency injection container, see cookbook for usage examples

**Comment by wdog** [comment]
I just added e simple minimal page to the [wiki](https://github.com/view-components/grids/wiki/Simple-Grid-Actions). Feel free to change everything
