### ISSUE TITLE
Static content / column with customer renderer

### ISSUE THREAD

**Issue by tyteen4a03** [view-components/grids#9]
I'm trying to make some buttons that would accompany the row (e.g Edit/Delete buttons). I'm looking at the Column class and it seems like I would have to implement a new Column Type, a new DataView and a custom Renderer.

This looks quite complicated if you just want something like `new DynamicColumn("fancy_things", $template = 'fancy_template.twig')` or the like. Could this be simplified?

**Comment by Nayjest** [comment]
Hi!
See https://github.com/view-components/grids/issues/7
You can return static content from anonymous function passed used in setValueCalculator method.

Also you can create your column class extended from Column & override constructor in following way:
1. parent constructor call
2. $this->dataView = new TemplateView('path-to-template');

Thats all

Renderer isn't required. Components always receives it from service locator if it wasn't provided. I just follow the rule saying that anything available in service locator should be possible to inject via constructor if users don't want to use service locator.

**Comment by Nayjest** [comment]
Also, if you are planning to use templates, see https://github.com/view-components/view-components/blob/master/doc/cookbook.md#3-how-to-use-custom-view-templates--override-core-templates

**Comment by Nayjest** [comment]
Hi!
Does this help?
Can we close this issue?

**Comment by tyteen4a03** [comment]
How can I pass a string as a template in this case?
